version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: node1
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  filebeat:
    image: elastic/filebeat:7.17.7
    container_name: filebeat
    depends_on:
      - logstash
      - elasticsearch
    volumes:
      - filebeat:/usr/share/filebeat/data
      - ./dockers/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /home/itarchitect/Work/Ruby/ads_microservice/log/:/var/log/ads:ro
      - /home/itarchitect/Work/Ruby/auth_microservice/log/:/var/log/auth:ro
      - /home/itarchitect/Work/Ruby/geocoder_microservice/log/:/var/log/geocoder:ro
  elasticsearch:
    image: elasticsearch:7.17.7
    container_name: elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ./dockers/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  logstash:
    image: logstash:7.17.7
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - logstash:/usr/share/logstash/data
      - ./dockers/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  kibana:
    image: kibana:7.17.7
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
  prom:
    image: prom/prometheus:v2.35.0
    container_name: prom
    # for node_exporter on Linux 
    network_mode: host
    # for node_exporter on  MacOS
    # network_mode must be empty
    ports:
      - 9090:9090
    volumes:
      - prometheus:/prometheus
      - ./dockers/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:8.5.15
    container_name: grafana
    ports:
      - 3005:3000
    volumes:
      - grafana:/var/lib/grafana
volumes:
  prometheus:
  grafana:
  rabbitmq:
  filebeat:
  elasticsearch:
  logstash:
