global:
  scrape_interval: 30s
scrape_configs:
  - job_name: node
    static_configs:
      # for grafana on Linux
      - targets: ['172.17.0.1:9100']
      # for node_exporter on Linux 
      # - targets: ['localhost:9100']
      # for node_exporter on  MacOS
      # - targets: ['host.docker.internal:9100']
  # - job_name: 'services'
  #   static_configs:
  #     - targets: ['host.docker.internal:3000', 'host.docker.internal:3020', 'host.docker.internal:3040']
