# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'puma'
gem 'rack'

gem 'rake'

gem 'config'
gem 'fast_jsonapi'
gem 'i18n', require: 'i18n'

gem 'activesupport', require: false

gem 'dry-initializer'
gem 'dry-validation'

gem 'faraday'

gem 'bunny'

gem 'amazing_print'
gem 'ougai', require: 'ougai'

gem 'prometheus-client'

group :development do
  gem 'pry'
end

group :development, :test do
  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
end

group :test do
  gem 'factory_bot'
  gem 'rspec'
end
