db:
  max_connections: 100
logger:
  path: log/production.log
  level: <%= Ougai::Logger::INFO %>
rabbitmq:
  host: <%= ENV.fetch('RABBITMQ_HOST') %>
  username: <%= ENV.fetch('RABBITMQ_USER') %>
  password: <%= ENV.fetch('RABBITMQ_PASSWORD') %>
